name: cmsc_23_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.7.0
  email_validator: ^2.1.17
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^19.1.54
  pie_chart: ^5.3.2
  intl: ^0.17.0
  flutter_svg: ^2.0.5
  http: ^0.13.6
  provider: ^6.0.5
  animated_bottom_navigation_bar: ^1.2.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  flutter_expandable_fab: ^1.8.0
  screenshot: ^2.1.0
  share: ^2.0.4
  path_provider: ^2.0.15
  image_gallery_saver: ^2.0.1
  permission_handler: ^10.2.1
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-UI-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-UI-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-UI-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-UI-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-UI-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-UI-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-UI-Display-Black.otf
          weight: 900
  assets:
    - assets/images/
